# .github/actions/build-and-deploy/action.yml
name: 'Build and deploy'
description: 'Build site with our custom jazz'
inputs:
  s3_bucket:
    required: true
  s3_access_key_id:
    required: true
  s3_secret_key:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    S3_BUCKET: ${{ inputs.s3_bucket }}
    S3_ACCESS_KEY_ID: ${{ inputs.s3_access_key_id }}
    S3_SECRET_KEY: ${{ inputs.s3_secret_key }}